export { AiAssistant } from "./components/ai-assistant";
export { CloudAvatar } from "./components/cloud-avatar";
export { CloudAssistant } from "./components/cloud-assistant";
export { SpeechBubble } from "./components/speech-bubble";
export { CloudChatPanel } from "./components/cloud-chat-panel";
export { Spotlight } from "./components/spotlight";
export { CloudProvider, useCloud } from "./context/cloud-provider";
export { useChatSession as useAiAssistant } from "./hooks/use-chat";
export { useDomScanner } from "./hooks/use-dom-scanner";
export { useCloudActions } from "./hooks/use-cloud-actions";
export { useProactiveTriggers } from "./hooks/use-proactive-triggers";
export { defaultTriggers } from "./lib/proactive-triggers";
export type { ChatMessage, ChatConfig, AssistantContext, ScannedElement } from "./types";
export type { CloudState, CloudMode, TourStep } from "./context/cloud-reducer";
export type { ProactiveTrigger, TriggerContext } from "./lib/proactive-triggers";
