import type { MCPServer, ProcessTemplate } from "../types";

// ─── MCP Server Catalog ─────────────────────────────────────────────
export const MCP_CATEGORIES = [
  "Regnskap",
  "Betaling",
  "Bank",
  "ERP",
  "Norske registre",
  "Egendefinerte",
] as const;

export const PREDEFINED_MCP_SERVERS: Omit<MCPServer, "id">[] = [
  {
    name: "Xero MCP",
    category: "Regnskap",
    description: "Xero regnskapssystem — faktura, kontakter, bankavstemminger",
    url: "https://mcp.xero.com",
    transport: "streamable-http",
    tools: [
      { name: "createInvoice", description: "Opprett faktura" },
      { name: "getContacts", description: "Hent kontaktliste" },
      { name: "reconcileBankTransaction", description: "Avstem banktransaksjon" },
    ],
    authType: "oauth",
    status: "active",
    icon: "receipt",
  },
  {
    name: "Tripletex API",
    category: "Regnskap",
    description: "Tripletex regnskapssystem for norske bedrifter",
    url: "https://tripletex.no/v2",
    transport: "streamable-http",
    tools: [
      { name: "createVoucher", description: "Opprett bilag" },
      { name: "getAccounts", description: "Hent kontoplan" },
      { name: "postJournalEntry", description: "Bokfør postering" },
    ],
    authType: "bearer",
    status: "active",
    icon: "calculator",
  },
  {
    name: "Visma eAccounting",
    category: "Regnskap",
    description: "Visma eAccounting for norske SMB-er",
    url: "https://eaccountingapi.vismaonline.com",
    transport: "streamable-http",
    tools: [
      { name: "createSupplierInvoice", description: "Registrer leverandørfaktura" },
      { name: "getVATReport", description: "Hent MVA-rapport" },
    ],
    authType: "oauth",
    status: "active",
    icon: "file-spreadsheet",
  },
  {
    name: "QuickBooks MCP",
    category: "Regnskap",
    description: "Intuit QuickBooks Online",
    url: "https://mcp.quickbooks.com",
    transport: "streamable-http",
    tools: [
      { name: "createExpense", description: "Registrer utgift" },
      { name: "createBill", description: "Opprett regning" },
    ],
    authType: "oauth",
    status: "active",
    icon: "book-open",
  },
  {
    name: "Stripe MCP",
    category: "Betaling",
    description: "Stripe betalingsbehandling",
    url: "https://mcp.stripe.com",
    transport: "streamable-http",
    tools: [
      { name: "createPaymentIntent", description: "Opprett betaling" },
      { name: "getBalance", description: "Hent saldo" },
      { name: "listTransactions", description: "List transaksjoner" },
    ],
    authType: "bearer",
    status: "active",
    icon: "credit-card",
  },
  {
    name: "Vipps MobilePay",
    category: "Betaling",
    description: "Vipps MobilePay betalingsløsning",
    url: "https://api.vipps.no",
    transport: "streamable-http",
    tools: [
      { name: "initiatePayment", description: "Start betaling" },
      { name: "capturePayment", description: "Fang betaling" },
    ],
    authType: "oauth",
    status: "active",
    icon: "smartphone",
  },
  {
    name: "DNB Open Banking",
    category: "Bank",
    description: "DNB Open Banking API-er",
    url: "https://developer.dnb.no",
    transport: "streamable-http",
    tools: [
      { name: "getAccounts", description: "Hent bankkontoer" },
      { name: "getTransactions", description: "Hent transaksjoner" },
    ],
    authType: "oauth",
    status: "active",
    icon: "landmark",
  },
  {
    name: "Sbanken API",
    category: "Bank",
    description: "Sbanken Open Banking API",
    url: "https://publicapi.sbanken.no",
    transport: "streamable-http",
    tools: [
      { name: "getAccounts", description: "Hent kontoer" },
      { name: "getTransactions", description: "Hent transaksjoner" },
      { name: "initiateTransfer", description: "Utfør overføring" },
    ],
    authType: "oauth",
    status: "active",
    icon: "building-2",
  },
  {
    name: "Dynamics 365 MCP",
    category: "ERP",
    description: "Microsoft Dynamics 365 Business Central",
    url: "https://mcp.dynamics.com",
    transport: "streamable-http",
    tools: [
      { name: "postGeneralJournalEntry", description: "Bokfør i hovedbok" },
      { name: "getCustomers", description: "Hent kunder" },
      { name: "createPurchaseOrder", description: "Opprett innkjøpsordre" },
    ],
    authType: "oauth",
    status: "active",
    icon: "database",
  },
  {
    name: "SAP Business One MCP",
    category: "ERP",
    description: "SAP Business One for SMB",
    url: "https://mcp.sap.com/b1",
    transport: "streamable-http",
    tools: [
      { name: "createJournalEntry", description: "Opprett bilag" },
      { name: "getBusinessPartners", description: "Hent forretningspartnere" },
    ],
    authType: "bearer",
    status: "active",
    icon: "server",
  },
  {
    name: "Brønnøysundregistrene",
    category: "Norske registre",
    description: "Enhetsregisteret, foretaksregisteret",
    url: "https://data.brreg.no",
    transport: "streamable-http",
    tools: [
      { name: "lookupOrganization", description: "Slå opp organisasjon" },
      { name: "getAnnouncements", description: "Hent kunngjøringer" },
    ],
    authType: "none",
    status: "active",
    icon: "building",
  },
  {
    name: "EHF / PEPPOL",
    category: "Norske registre",
    description: "Elektronisk handel — faktura og kreditnota",
    url: "https://ehf.difi.no",
    transport: "streamable-http",
    tools: [
      { name: "sendInvoice", description: "Send EHF-faktura" },
      { name: "validateDocument", description: "Valider EHF-dokument" },
    ],
    authType: "bearer",
    status: "active",
    icon: "file-check",
  },
];

// ─── Process Templates ──────────────────────────────────────────────
export const PROCESS_TEMPLATES: Omit<ProcessTemplate, "id" | "createdBy" | "createdAt">[] = [
  {
    name: "Fakturamottak og kontering",
    description: "Automatisert mottak, scanning, kontering og godkjenning av leverandørfakturaer.",
    category: "Regnskap",
    tags: ["faktura", "kontering", "leverandør", "AP"],
    usageCount: 0,
    definition: {
      name: "Fakturamottak og kontering",
      description: "Automatisert fakturamottak med AI-kontering",
      version: 1,
      status: "published",
      nodes: [
        { id: "start", type: "startEvent", label: "Faktura mottas", position: { x: 0, y: 150 }, metadata: {} },
        { id: "scan", type: "serviceTask", label: "OCR-scanning", position: { x: 200, y: 150 }, agentConfig: { autonomyLevel: 5, llmPrompt: "Ekstraher fakturadata via OCR", tools: ["ocr"], maxIterations: 3, timeout: 30000, humanApprovalRequired: false }, metadata: {} },
        { id: "konter", type: "serviceTask", label: "AI-kontering", position: { x: 400, y: 150 }, agentConfig: { autonomyLevel: 3, llmPrompt: "Kontér faktura basert på kontoplan og historikk", tools: ["accounting"], maxIterations: 5, timeout: 30000, humanApprovalRequired: false }, metadata: {} },
        { id: "gw_amount", type: "exclusiveGateway", label: "Beløp > 100k?", position: { x: 600, y: 150 }, metadata: {} },
        { id: "approve", type: "userTask", label: "Manuell godkjenning", position: { x: 800, y: 50 }, metadata: {} },
        { id: "book", type: "serviceTask", label: "Bokfør", position: { x: 800, y: 250 }, agentConfig: { autonomyLevel: 4, llmPrompt: "Bokfør faktura i regnskapssystemet", tools: ["tripletex"], maxIterations: 3, timeout: 30000, humanApprovalRequired: false }, metadata: {} },
        { id: "end", type: "endEvent", label: "Ferdig", position: { x: 1000, y: 150 }, metadata: {} },
      ],
      edges: [
        { id: "e1", source: "start", target: "scan" },
        { id: "e2", source: "scan", target: "konter" },
        { id: "e3", source: "konter", target: "gw_amount" },
        { id: "e4", source: "gw_amount", target: "approve", condition: "amount > 100000", label: "Ja" },
        { id: "e5", source: "gw_amount", target: "book", condition: "amount <= 100000", label: "Nei" },
        { id: "e6", source: "approve", target: "book" },
        { id: "e7", source: "book", target: "end" },
      ],
      tags: ["faktura", "kontering"],
      isTemplate: true,
    },
  },
  {
    name: "Bankavstemmingsprosess",
    description: "Automatisk avstemming av banktransaksjoner mot bokførte poster.",
    category: "Regnskap",
    tags: ["bank", "avstemming", "reconciliation"],
    usageCount: 0,
    definition: {
      name: "Bankavstemmingsprosess",
      description: "Automatisk bankavtemming med AI-matching",
      version: 1,
      status: "published",
      nodes: [
        { id: "start", type: "startEvent", label: "Planlagt kjøring", position: { x: 0, y: 150 }, metadata: {} },
        { id: "fetch", type: "serviceTask", label: "Hent transaksjoner", position: { x: 200, y: 150 }, agentConfig: { autonomyLevel: 5, llmPrompt: "Hent banktransaksjoner fra Open Banking API", tools: ["dnb", "sbanken"], maxIterations: 3, timeout: 60000, humanApprovalRequired: false }, metadata: {} },
        { id: "match", type: "serviceTask", label: "AI-matching", position: { x: 400, y: 150 }, agentConfig: { autonomyLevel: 3, llmPrompt: "Match banktransaksjoner mot bokførte poster", tools: ["accounting"], maxIterations: 10, timeout: 120000, humanApprovalRequired: false }, metadata: {} },
        { id: "gw_unmatched", type: "exclusiveGateway", label: "Uavstemt?", position: { x: 600, y: 150 }, metadata: {} },
        { id: "review", type: "userTask", label: "Manuell gjennomgang", position: { x: 800, y: 50 }, metadata: {} },
        { id: "report", type: "serviceTask", label: "Generer rapport", position: { x: 800, y: 250 }, agentConfig: { autonomyLevel: 5, llmPrompt: "Generer avstemmingsrapport", tools: [], maxIterations: 1, timeout: 30000, humanApprovalRequired: false }, metadata: {} },
        { id: "end", type: "endEvent", label: "Ferdig", position: { x: 1000, y: 150 }, metadata: {} },
      ],
      edges: [
        { id: "e1", source: "start", target: "fetch" },
        { id: "e2", source: "fetch", target: "match" },
        { id: "e3", source: "match", target: "gw_unmatched" },
        { id: "e4", source: "gw_unmatched", target: "review", condition: "hasUnmatched", label: "Ja" },
        { id: "e5", source: "gw_unmatched", target: "report", condition: "!hasUnmatched", label: "Nei" },
        { id: "e6", source: "review", target: "report" },
        { id: "e7", source: "report", target: "end" },
      ],
      tags: ["bank", "avstemming"],
      isTemplate: true,
    },
  },
  {
    name: "MVA-oppgjør og rapportering",
    description: "Automatisert beregning og rapportering av MVA til Skatteetaten.",
    category: "Regnskap",
    tags: ["mva", "skatt", "rapportering"],
    usageCount: 0,
    definition: {
      name: "MVA-oppgjør",
      description: "Automatisert MVA-beregning og innsending",
      version: 1,
      status: "published",
      nodes: [
        { id: "start", type: "startEvent", label: "Termin utløper", position: { x: 0, y: 150 }, metadata: {} },
        { id: "collect", type: "serviceTask", label: "Samle MVA-data", position: { x: 200, y: 150 }, agentConfig: { autonomyLevel: 5, llmPrompt: "Hent alle MVA-transaksjoner for perioden", tools: ["accounting"], maxIterations: 3, timeout: 60000, humanApprovalRequired: false }, metadata: {} },
        { id: "calculate", type: "serviceTask", label: "Beregn MVA", position: { x: 400, y: 150 }, agentConfig: { autonomyLevel: 4, llmPrompt: "Beregn MVA-grunnlag og avgift per sats", tools: [], maxIterations: 5, timeout: 30000, humanApprovalRequired: false }, metadata: {} },
        { id: "review", type: "userTask", label: "Revisor kontroll", position: { x: 600, y: 150 }, metadata: {} },
        { id: "submit", type: "serviceTask", label: "Send til Altinn", position: { x: 800, y: 150 }, agentConfig: { autonomyLevel: 2, llmPrompt: "Send MVA-melding via Altinn API", tools: ["altinn"], maxIterations: 3, timeout: 30000, humanApprovalRequired: true }, metadata: {} },
        { id: "end", type: "endEvent", label: "Innsendt", position: { x: 1000, y: 150 }, metadata: {} },
      ],
      edges: [
        { id: "e1", source: "start", target: "collect" },
        { id: "e2", source: "collect", target: "calculate" },
        { id: "e3", source: "calculate", target: "review" },
        { id: "e4", source: "review", target: "submit" },
        { id: "e5", source: "submit", target: "end" },
      ],
      tags: ["mva", "skatt"],
      isTemplate: true,
    },
  },
  {
    name: "Lønnskjøring",
    description: "Komplett lønnskjøring med beregning, godkjenning og utbetaling.",
    category: "Regnskap",
    tags: ["lønn", "payroll", "arbeidsgiveravgift"],
    usageCount: 0,
    definition: {
      name: "Lønnskjøring",
      description: "Automatisert lønnskjøring",
      version: 1,
      status: "published",
      nodes: [
        { id: "start", type: "startEvent", label: "Lønnsdag", position: { x: 0, y: 150 }, metadata: {} },
        { id: "collect", type: "serviceTask", label: "Hent timelister", position: { x: 200, y: 150 }, agentConfig: { autonomyLevel: 5, llmPrompt: "Hent timelister og fravær", tools: ["hr"], maxIterations: 3, timeout: 30000, humanApprovalRequired: false }, metadata: {} },
        { id: "calculate", type: "serviceTask", label: "Beregn lønn", position: { x: 400, y: 150 }, agentConfig: { autonomyLevel: 4, llmPrompt: "Beregn bruttolønn, skatt, og netto", tools: ["payroll"], maxIterations: 5, timeout: 60000, humanApprovalRequired: false }, metadata: {} },
        { id: "approve", type: "userTask", label: "Godkjenn lønn", position: { x: 600, y: 150 }, metadata: {} },
        { id: "pay", type: "serviceTask", label: "Utbetal", position: { x: 800, y: 150 }, agentConfig: { autonomyLevel: 2, llmPrompt: "Utfør lønnsutbetaling", tools: ["bank"], maxIterations: 3, timeout: 30000, humanApprovalRequired: true }, metadata: {} },
        { id: "end", type: "endEvent", label: "Utbetalt", position: { x: 1000, y: 150 }, metadata: {} },
      ],
      edges: [
        { id: "e1", source: "start", target: "collect" },
        { id: "e2", source: "collect", target: "calculate" },
        { id: "e3", source: "calculate", target: "approve" },
        { id: "e4", source: "approve", target: "pay" },
        { id: "e5", source: "pay", target: "end" },
      ],
      tags: ["lønn"],
      isTemplate: true,
    },
  },
  {
    name: "Månedsavslutning",
    description: "Komplett sjekkliste og automatisering av månedsavslutning.",
    category: "Regnskap",
    tags: ["månedsavslutning", "periodeavslutning"],
    usageCount: 0,
    definition: {
      name: "Månedsavslutning",
      description: "Automatisert månedsavslutning",
      version: 1,
      status: "published",
      nodes: [
        { id: "start", type: "startEvent", label: "Måned slutt", position: { x: 0, y: 200 }, metadata: {} },
        { id: "reconcile", type: "serviceTask", label: "Bankavtemming", position: { x: 200, y: 200 }, agentConfig: { autonomyLevel: 4, llmPrompt: "Kjør bankavtemming for alle kontoer", tools: ["bank", "accounting"], maxIterations: 10, timeout: 120000, humanApprovalRequired: false }, metadata: {} },
        { id: "accrue", type: "serviceTask", label: "Periodiseringer", position: { x: 400, y: 200 }, agentConfig: { autonomyLevel: 3, llmPrompt: "Beregn og bokfør periodiseringer", tools: ["accounting"], maxIterations: 5, timeout: 60000, humanApprovalRequired: false }, metadata: {} },
        { id: "review", type: "userTask", label: "Kontroller", position: { x: 600, y: 200 }, metadata: {} },
        { id: "close", type: "serviceTask", label: "Lukk periode", position: { x: 800, y: 200 }, agentConfig: { autonomyLevel: 2, llmPrompt: "Lukk regnskapsperioden", tools: ["accounting"], maxIterations: 1, timeout: 30000, humanApprovalRequired: true }, metadata: {} },
        { id: "end", type: "endEvent", label: "Lukket", position: { x: 1000, y: 200 }, metadata: {} },
      ],
      edges: [
        { id: "e1", source: "start", target: "reconcile" },
        { id: "e2", source: "reconcile", target: "accrue" },
        { id: "e3", source: "accrue", target: "review" },
        { id: "e4", source: "review", target: "close" },
        { id: "e5", source: "close", target: "end" },
      ],
      tags: ["månedsavslutning"],
      isTemplate: true,
    },
  },
  {
    name: "Årsoppgjør",
    description: "Komplett årsoppgjørsprosess med skattemelding og årsregnskap.",
    category: "Regnskap",
    tags: ["årsoppgjør", "skattemelding", "årsregnskap"],
    usageCount: 0,
    definition: {
      name: "Årsoppgjør",
      description: "Automatisert årsoppgjør",
      version: 1,
      status: "published",
      nodes: [
        { id: "start", type: "startEvent", label: "År slutt", position: { x: 0, y: 200 }, metadata: {} },
        { id: "close_months", type: "serviceTask", label: "Lukk alle perioder", position: { x: 200, y: 200 }, agentConfig: { autonomyLevel: 3, llmPrompt: "Verifiser og lukk alle åpne perioder", tools: ["accounting"], maxIterations: 5, timeout: 60000, humanApprovalRequired: false }, metadata: {} },
        { id: "adjustments", type: "serviceTask", label: "Årsoppgjørsposter", position: { x: 400, y: 200 }, agentConfig: { autonomyLevel: 2, llmPrompt: "Beregn avskrivninger, skatt, og spesialposter", tools: ["accounting"], maxIterations: 10, timeout: 120000, humanApprovalRequired: false }, metadata: {} },
        { id: "review", type: "userTask", label: "Revisor gjennomgang", position: { x: 600, y: 200 }, metadata: {} },
        { id: "submit", type: "serviceTask", label: "Send skattemelding", position: { x: 800, y: 200 }, agentConfig: { autonomyLevel: 1, llmPrompt: "Generer og send skattemelding via Altinn", tools: ["altinn"], maxIterations: 3, timeout: 60000, humanApprovalRequired: true }, metadata: {} },
        { id: "end", type: "endEvent", label: "Ferdig", position: { x: 1000, y: 200 }, metadata: {} },
      ],
      edges: [
        { id: "e1", source: "start", target: "close_months" },
        { id: "e2", source: "close_months", target: "adjustments" },
        { id: "e3", source: "adjustments", target: "review" },
        { id: "e4", source: "review", target: "submit" },
        { id: "e5", source: "submit", target: "end" },
      ],
      tags: ["årsoppgjør"],
      isTemplate: true,
    },
  },
];

// ─── Layout Constants ───────────────────────────────────────────────
export const LAYOUT_DEFAULTS = {
  direction: "LR" as const,
  nodeWidth: 180,
  nodeHeight: 60,
  rankSep: 80,
  nodeSep: 50,
};

// ─── Keyboard Shortcuts ─────────────────────────────────────────────
export const KEYBOARD_SHORTCUTS = {
  focusChat: "mod+1",
  focusCanvas: "mod+2",
  focusProperties: "mod+3",
  toggleFullscreen: "mod+shift+f",
  autoLayout: "mod+shift+l",
  validate: "mod+shift+v",
  deploy: "mod+shift+d",
  undo: "mod+z",
  redo: "mod+shift+z",
};
